### PR TITLE
:sparkles: Open GitLab merge request page

### PR DESCRIPTION
**Pull request by kitagry**
Add GitLab pull request URL

## Summary by CodeRabbit

- **New Features**
	- Introduced an optional method to extract Pull Request ID from commit messages across different hosting services.
	- Enhanced functionality to retrieve Pull Request URLs and IDs for GitLab-hosted repositories.
	- Updated the `pull_request_url.ts` code to incorporate the new `hostingService` parameter for extracting Pull Request IDs.

### CODE REVIEW

**Comment by lambdalisue** [comment]
@kitagry CI was disabled and there was a lint issue so could you rebase from the current `main`?

**Comment by kitagry** [comment]
Hmm, snapshot test is not correct 🤔 

If you don't mind, I will rewrite exact value test instead of snapshot test. Do you think about this?

**Comment by lambdalisue** [comment]
> Hmm, snapshot test is not correct 🤔

What do you mean "not correct"? Did you update snapshot?

**Comment by kitagry** [comment]
I'm sorry, I misunderstand :pray:

I'll update snapshot. :bow:

**Comment by kitagry** [comment]
Hi @lambdalisue . Could you review this?

**Review by lambdalisue — APPROVED** [review]

**Comment by lambdalisue** [comment]
Thanks 🎉

**Pull request merged**
